name: Build and deploy Node.js app to Azure Web App - careasa1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir deployment-package
          shopt -s extglob
          cp -r !(deployment-package|node_modules|.git|release.zip) deployment-package/
          zip -r release.zip deployment-package

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Wait to avoid SCM conflict
        run: sleep 15

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'careasa1'
          slot-name: 'Production'
          package: deployment-package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_39F0E1E1EC0949F6857EB3D7CA6E2E91 }}
